name: Verify Gem Version Change

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Version Check
    runs-on: ubuntu-latest

    steps:
    - name: Version Forget Me Not
      uses: simplybusiness/version-forget-me-not@v2
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION_FILE_PATH: "lib/hologram/version.rb"
